### ISSUE TITLE
NPE "address" field in VertxHttpClientMetrics::Handler is null

### ISSUE THREAD

**Issue by ashcor** [vert-x3/vertx-micrometer-metrics#128]
### Version

4.1.5

### Context

```
> 2021-10-07T11:25:40.864144+00:00 app[web.1]: 11:25:40.863 [vert.x-eventloop-thread-1] ERROR i.vertx.core.net.impl.ConnectionBase - Cannot read field "address" because "x0" is null
  2021-10-07T11:25:40.864152+00:00 app[web.1]: java.lang.NullPointerException: Cannot read field "address" because "x0" is null
> 2021-10-07T11:25:40.864153+00:00 app[web.1]: at io.vertx.micrometer.impl.VertxHttpClientMetrics$Handler.access$800(VertxHttpClientMetrics.java:141)
> 2021-10-07T11:25:40.864153+00:00 app[web.1]: at io.vertx.micrometer.impl.VertxHttpClientMetrics$Instance$1.requestReset(VertxHttpClientMetrics.java:105)
> 2021-10-07T11:25:40.864154+00:00 app[web.1]: at io.vertx.micrometer.impl.VertxHttpClientMetrics$Instance$1.requestReset(VertxHttpClientMetrics.java:76)
> 2021-10-07T11:25:40.864154+00:00 app[web.1]: at io.vertx.core.http.impl.Http1xClientConnection.handleClosed(Http1xClientConnection.java:1084)
> 2021-10-07T11:25:40.864155+00:00 app[web.1]: at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:144)
  2021-10-07T11:25:40.864155+00:00 app[web.1]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
  2021-10-07T11:25:40.864156+00:00 app[web.1]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
  2021-10-07T11:25:40.864156+00:00 app[web.1]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
  2021-10-07T11:25:40.864156+00:00 app[web.1]: at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418)
  2021-10-07T11:25:40.864157+00:00 app[web.1]: at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
  2021-10-07T11:25:40.864157+00:00 app[web.1]: at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
  2021-10-07T11:25:40.864158+00:00 app[web.1]: at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:326)
  2021-10-07T11:25:40.864158+00:00 app[web.1]: at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221)
  2021-10-07T11:25:40.864159+00:00 app[web.1]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
  2021-10-07T11:25:40.864159+00:00 app[web.1]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
  2021-10-07T11:25:40.864159+00:00 app[web.1]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
  2021-10-07T11:25:40.864160+00:00 app[web.1]: at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
  2021-10-07T11:25:40.864160+00:00 app[web.1]: at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
  2021-10-07T11:25:40.864160+00:00 app[web.1]: at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1074)
  2021-10-07T11:25:40.864160+00:00 app[web.1]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
  2021-10-07T11:25:40.864161+00:00 app[web.1]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
  2021-10-07T11:25:40.864161+00:00 app[web.1]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
  2021-10-07T11:25:40.864161+00:00 app[web.1]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
  2021-10-07T11:25:40.864162+00:00 app[web.1]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
  2021-10-07T11:25:40.864162+00:00 app[web.1]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
  2021-10-07T11:25:40.864163+00:00 app[web.1]: at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
  2021-10-07T11:25:40.864163+00:00 app[web.1]: at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
  2021-10-07T11:25:40.864163+00:00 app[web.1]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
  2021-10-07T11:25:40.864164+00:00 app[web.1]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
  2021-10-07T11:25:40.864164+00:00 app[web.1]: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
  2021-10-07T11:25:40.864164+00:00 app[web.1]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
  2021-10-07T11:25:40.864165+00:00 app[web.1]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  2021-10-07T11:25:40.864165+00:00 app[web.1]: at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  2021-10-07T11:25:40.864166+00:00 app[web.1]: at java.base/java.lang.Thread.run(Thread.java:831)
```

### Do you have a reproducer?

No, unfortunately not. 

### Extra

Getting this error when upgrading from vertx 3.9.9 to 4.1.5. We have one Influx registry configured for mircrometer. Only getting the error when running on heroku (Java 16).

Metrics are initialized with 
```
@Bean
    public Vertx vertx(MeterRegistry registry) {

        registry.config()
                .commonTags("app", "myapp");

        VertxOptions options = new VertxOptions()
                .setMetricsOptions(new MicrometerMetricsOptions()
                        .setMicrometerRegistry(registry)
                        .setEnabled(true)
                );
        return Vertx.vertx(options);
    }
```

**Comment by ashcor** [comment]
From my observations a race condition could be the cause. I've only observed the issue under heavy load.

**Comment by vietj** [comment]
the only case I can see is that a request has been scheduled by the client but not yet sent, so the metric is not yet there

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/pull/4159

**Comment by vietj** [comment]
it will also be in 4.1.6
