### ISSUE TITLE
Pool metrics ClassCastException

### ISSUE THREAD

**Issue by bschev** [vert-x3/vertx-micrometer-metrics#165]
### Versions

`4.3.5`,`4.3.6`,`4.3.7`

### Context

I get once for the first scrape one of the following warnings:

```
2023-01-13 11:32:43,214 WARN i.m.c.i.i.DefaultGauge [vert.x-eventloop-thread-0] Failed to apply the value function for the gauge 'vertx.pool.in.use'. Note that subsequent logs will be logged at debug level. 
java.lang.ClassCastException: class java.util.concurrent.atomic.AtomicReference cannot be cast to class java.util.concurrent.atomic.LongAdder (java.util.concurrent.atomic.AtomicReference and java.util.concurrent.atomic.LongAdder are in module java.base of loader 'bootstrap')
    at io.vertx.micrometer.impl.meters.Gauges$ValueSupplier.get(Gauges.java:125)
    at io.vertx.micrometer.impl.meters.Gauges$ValueSupplier.get(Gauges.java:108)
    at io.micrometer.core.instrument.Gauge.lambda$builder$0(Gauge.java:58)
    at io.micrometer.core.instrument.StrongReferenceGaugeFunction.applyAsDouble(StrongReferenceGaugeFunction.java:48)
    at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:53)
    at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$newGauge$5(PrometheusMeterRegistry.java:331)
    at io.micrometer.prometheus.MicrometerCollector.collect(MicrometerCollector.java:75)
    at io.prometheus.client.Collector.collect(Collector.java:45)
    at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:204)
    at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:219)
    at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:152)
    at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:71)
    at io.prometheus.client.exporter.common.TextFormat.writeFormat(TextFormat.java:53)
    at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:154)
    at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:149)
    at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:120)
    at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:107)
```
```
2023-01-13 11:30:23,907 WARN i.m.c.i.i.DefaultGauge [vert.x-eventloop-thread-0] Failed to apply the value function for the gauge 'vertx.pool.ratio'. Note that subsequent logs will be logged at debug level. 
java.lang.ClassCastException: class java.util.concurrent.atomic.AtomicReference cannot be cast to class java.util.concurrent.atomic.LongAdder (java.util.concurrent.atomic.AtomicReference and java.util.concurrent.atomic.LongAdder are in module java.base of loader 'bootstrap')
    at io.vertx.micrometer.impl.meters.Gauges$ValueSupplier.get(Gauges.java:125)
    at io.vertx.micrometer.impl.meters.Gauges$ValueSupplier.get(Gauges.java:108)
    at io.micrometer.core.instrument.Gauge.lambda$builder$0(Gauge.java:58)
    at io.micrometer.core.instrument.StrongReferenceGaugeFunction.applyAsDouble(StrongReferenceGaugeFunction.java:48)
    at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:53)
    at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$newGauge$5(PrometheusMeterRegistry.java:331)
    at io.micrometer.prometheus.MicrometerCollector.collect(MicrometerCollector.java:75)
    at io.prometheus.client.Collector.collect(Collector.java:45)
    at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:204)
    at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:219)
    at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:152)
    at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:71)
    at io.prometheus.client.exporter.common.TextFormat.writeFormat(TextFormat.java:53)
    at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:154)
    at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:149)
    at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:120)
    at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:107)
```

It seems random if `vertx.pool.in.use` or `vertx.pool.ratio` is causing the problem. 

The app has two pool types 'worker' and 'redis'.

Prometheus scrape result for this gauges:
```
# HELP vertx_pool_in_use Number of resources used
# TYPE vertx_pool_in_use gauge
vertx_pool_in_use{pool_type="worker",} 0.0
vertx_pool_in_use{pool_type="redis",} NaN
# HELP vertx_pool_ratio Pool usage ratio, only present if maximum pool size could be determined
# TYPE vertx_pool_ratio gauge
vertx_pool_ratio{pool_type="worker",} 0.0
vertx_pool_ratio{pool_type="redis",} NaN
```

### Steps to reproduce

The culprit seems to be the 'redis' pool type. I can't reproduce it only with a worker, but it is reproducible only with a redis client. 

1. Provide redis on localhost
`docker run -p 6379:6379 --rm -it redis:latest`

2. Start embedded Prometheus server and create a redis connection
```java
Vertx vertx = Vertx.vertx(new VertxOptions().setMetricsOptions(
  new MicrometerMetricsOptions()
    .setPrometheusOptions(new VertxPrometheusOptions().setEnabled(true)
      .setStartEmbeddedServer(true)
      .setEmbeddedServerOptions(new HttpServerOptions().setPort(8080))
      .setEmbeddedServerEndpoint("/metrics/vertx"))
    .setEnabled(true)));

Redis.createClient(vertx, new RedisOptions()).connect();
```

3. Make metrics request - this request will cause the `ClassCastException`
```
curl http://localhost:8080/metrics/vertx

# HELP vertx_pool_ratio Pool usage ratio, only present if maximum pool size could be determined
# TYPE vertx_pool_ratio gauge
vertx_pool_ratio{pool_type="redis",} NaN
# HELP vertx_pool_queue_pending Number of pending elements in queue
# TYPE vertx_pool_queue_pending gauge
vertx_pool_queue_pending{pool_type="redis",} 0.0
# HELP vertx_net_client_active_connections Number of connections to the remote host currently opened
# TYPE vertx_net_client_active_connections gauge
vertx_net_client_active_connections 1.0
# HELP vertx_pool_in_use Number of resources used
# TYPE vertx_pool_in_use gauge
vertx_pool_in_use{pool_type="redis",} NaN
# HELP vertx_pool_queue_time_seconds_max Time spent in queue before being processed
# TYPE vertx_pool_queue_time_seconds_max gauge
vertx_pool_queue_time_seconds_max{pool_type="redis",} 0.083685959
# HELP vertx_pool_queue_time_seconds Time spent in queue before being processed
# TYPE vertx_pool_queue_time_seconds summary
vertx_pool_queue_time_seconds_count{pool_type="redis",} 1.0
vertx_pool_queue_time_seconds_sum{pool_type="redis",} 0.083685959
```

**Comment by tsegismont** [comment]
This is a regression introduced in `4.3.5` by  #158. I will fix it and backport to `4.3` branch

**Comment by tsegismont** [comment]
Fixed by d597084

**Comment by tsegismont** [comment]
@bschev if you can test with `4.3.8-SNAPSHOT`, I would appreciate any feedback you may have. Thank you

**Comment by bschev** [comment]
@tsegismont Looks to me like the last `4.3.8-SNAPSHOT` deployment failed: https://github.com/vert-x3/vertx-micrometer-metrics/actions/runs/3989211912

**Comment by tsegismont** [comment]
Thanks for the heads-up @bschev ! I've restarted the deployment job.

**Comment by tsegismont** [comment]
Thank **you** for taking some time to make a good report and for the feedback
