### ISSUE TITLE
Build failure due to PrometheusMetricsITest.shouldBindExistingServer

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-micrometer-metrics#58]
https://travis-ci.org/vert-x3/vertx-micrometer-metrics/jobs/452269867

```
Running io.vertx.micrometer.backend.PrometheusMetricsITest
[vert.x-eventloop-thread-3] 2018-11-08T08:15:24.15Z SEVERE [io.vertx.core.http.impl.HttpClientRequestImpl]  io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8081
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:9090
retrying...
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.635 sec <<< FAILURE! - in io.vertx.micrometer.backend.PrometheusMetricsITest
shouldBindExistingServer(io.vertx.micrometer.backend.PrometheusMetricsITest)  Time elapsed: 10.037 sec  <<< ERROR!
java.util.concurrent.TimeoutException: Timed out
	at io.vertx.ext.unit.impl.CompletionImpl.awaitSuccess(CompletionImpl.java:99)
	at io.vertx.micrometer.backend.PrometheusMetricsITest.shouldBindExistingServer(PrometheusMetricsITest.java:98)
```

**Comment by jotak** [comment]
I think I'll have to increase the timeouts :(

**Comment by jotak** [comment]
fixed with https://github.com/vert-x3/vertx-micrometer-metrics/commit/73f43b0886445d0b46545181bd87306767e530be
